### PR TITLE
Update two_joshua_drew_dylan_caroline.md

### PR DESCRIPTION
**Pull request by dylanavery720**

### CODE REVIEW

**Review by case-eee — COMMENTED** [review]
Hey group 2,

The only update from the original session I see is removing one of the videos from the pre-reading. 

* How are you going to group students?
* Who is going to send out the pre-reading to students?
* How will you ensure students will stay on track during their discussion?

**Comment by Dpalazzari** [comment]
@case-eee 

1) I'll do a count off
2) I can send it out the day before
3) Unsure. Hopefully they will respect the fact that gear-ups are important and that the topic is important.

**Comment by case-eee** [comment]
Awesome @Dpalazzari - thanks for the clarification. Y'all will be in the F3 room for the session with the following M2/3 students:
* Joseph Glass, Leta Keane, Victoria Vasys, Danny Radden, Charlotte Moore, Kenia Farias, James Anderson, Christopher Jordan, Staci McWilliams

**Comment by case-eee** [comment]
@Dpalazzari Also - you may want to have your discussion questions written on the board or paper or something so that students can refer to them while they're watching the videos 👍

**Comment by dylanavery720** [comment]
Sounds good.

**Pull request merged**
