### PR TITLE
Add Gear-up: Gender diversity in the workplace

### PR DESCRIPTION
**Pull request by erinnachen**
@jcasimir @julyytran @bethsebian 
Please take a look at this draft, it seems a bit lengthy but I don't know where to cut. Comments/suggestions welcome.

### CODE REVIEW

**Comment by julyytran** [comment]
@erinnachen I love your enthusiasm here! Got a couple notes:
1. Too much math. I would not be able to finish the first two readings in 15 minutes myself, and my eyes kind of glazed over looking at the section where I had to do actually do math. I agree with you that there is great value in looking at data, but I think this presentation of it is very inaccessible. My specific suggestions on how to present them more effectively hinges on the next note, but in general, if the best media I've got is long and academic, I try to just select excerpts from them for reading to guide people, else they probably won't read it at all. You're trying to tackle a lot by addressing several issues under the umbrella theme AND including the maths. It's a hard balance to strike; I appreciate the gravity of that and I also struggle with that in crafting these types of things. 
2. What is your goal with this? Are you searching to present information/viewpoints and promote discussion, or push people to take actions? How do your goals and desired approach differ from the existing Gear Up related to gender in tech? (https://github.com/turingschool/gear-up/blob/master/gender_and_computer_science.markdown)
3. I think the media and questions in the "I'm not female, but I CAN also bring diversity to the table" section are great; short but very informative. 
4. For the lowering the bar section, I think it's important to remember that some people may have never even heard about this concept, and others may not know the full nuances of it. That could be a whole discussion unto itself. 
5. Some of our feedback has been that people like for questions to be Turing/tech industry related, so I like where you were heading with the exercises. I think that the information would be more digestible if the numerical exercises were simplified and condensed into one question. 

I think the next steps would be to go back through this from the perspective of a person who does not already know about any of these issues and finds math scary and deterring, and consider what is it that you want out of them -awareness? action? and then try to craft to that audience with that goal in mind. Then, I suggest going through again from the perspective of a skeptic/apathetic person and try to improve it based on that target audience and what you want out of them. Pretty much envision every kind of person in the basement and think about how best you can get what you want out of them :P

I'm happy to take another look after you review. Thanks for your work!

**Comment by erinnachen** [comment]
@julyytran Do you think a diagram like this would help?
image

**Comment by julyytran** [comment]
@erinnachen yes!

**Comment by julyytran** [comment]
I really like the changes made, @erinnachen , nice job. I think there is still too much content to fit in the session here right now though, especially if 
(1) we are asking people to make calculations (although simple, I think it'll take longer than 5 mins, but it might speed up the process if you give people the formula to calculate). I'm also on the fence about asking them to make calculations; it's definitely more engaging if people do it, but some people may just not do it. 
and (2) if you are going to allude to discrimination/harassment that women in tech experience, which is a huge topic in itself

I think you might consider changing the format such that each of the three sections is an option for a person in a group to take, and each group should have at least 1 person do each option, and then they can share and discuss. I would also consider abstracting the info on discrimination that women experience into the intro, as a sort of background premise FYI. I think that's a meaty topic that deserves another deep gear up itself, seeing how this is focused on economics and benefit to companies/society. I'd change the title to reflect that as well, in addition to cleaning up the overall language in terms of grammar and tone.

**Pull request merged**
